### ISSUE TITLE
add INTERVAL does not work for me

### ISSUE THREAD

**Issue by mcaj** [smithfarm/dochazka-cli#5]
I tried to add there an internal via the documentation https://metacpan.org/pod/App::Dochazka::CLI::Guide but it did not work for me:

Dochazka(2015-07-27) mcaj ACTIVE> INTERVAL 2015-07-27 08:00 - 2015-07-27 12:00 WORK work on dochazka-cli
Command not recognized (parse error)

do I need to active/set up a month ? tried to this:

Dochazka(2015-07-27) mcaj ACTIVE> internal fetch 7
*** REST ERROR ***

Error encountered on attempted operation "Get intervals for employee mcaj (EID 50) in range ( 2015-07-01 00:00, 2015-07-31 24:00 )"
REST operation: GET interval/eid/50/( 2015-07-01 00:00, 2015-07-31 24:00 )
HTTP status: 404 Not Found
Explanation: DISPATCH_NOTHING_IN_TSRANGE: No attendance intervals found in given tsrange
Permanent? YES

Dochazka(2015-07-27) mcaj ACTIVE> internal fetch july
*** REST ERROR ***

Error encountered on attempted operation "Get intervals for employee mcaj (EID 50) in range ( 2015-07-01 00:00, 2015-07-31 24:00 )"
REST operation: GET interval/eid/50/( 2015-07-01 00:00, 2015-07-31 24:00 )
HTTP status: 404 Not Found
Explanation: DISPATCH_NOTHING_IN_TSRANGE: No attendance intervals found in given tsrange
Permanent? YES

**Comment by smithfarm** [comment]
@mcaj Thanks! I just released `App::Dochazka::CLI` version 0.206 with a fix for this bug.
