### ISSUE TITLE
missing the perl  Text::Table modul 

### ISSUE THREAD

**Issue by mcaj** [smithfarm/dochazka-cli#6]
I was testing the installation how to:

$ sudo zypper ar http://download.opensuse.org/repositories/home:smithfarm/$DISTRO/home:smithfarm.repo
$ sudo zypper ref
$ sudo zypper in perl-App-Dochazka-CLI

end up with missing perl module:

Problem: nothing provides perl(Text::Table) needed by perl-App-Dochazka-CLI-0.204-1.1.noarch
Solution 1: do not install perl-App-Dochazka-CLI-0.204-1.1.noarch
Solution 2: break perl-App-Dochazka-CLI-0.204-1.1.noarch by ignoring some of its dependencies

The workaround solution is add there OBS devel repo:

$ sudo zypper ar http://download.opensuse.org/repositories/devel:/languages:/perl/$DISTRO/devel:languages:perl.repo
$ sudo zypper ref;sudo zypper in perl-App-Dochazka-CLI

**Comment by smithfarm** [comment]
@mcaj Thanks - today I found how I should have been building the packages in OBS since the beginning, i.e. linkpac all the needed dependencies from `devel:languages:perl` into `home:smithfarm` - working on that now.

I don't want to require users to install `devel:languages:perl` repo. . .

**Comment by smithfarm** [comment]
Fixed by linkpac'ing the missing dependencies.
